<div class="grid_12">
	<h1>Webmail</h1>
	<p>Configurações para acesso de API cPanel</p>
</div>
<div class="grid_12">
	<a class="button" href="<?php echo $this->url(array("module"=>"configuracao","controller"=>"webmail","action"=>"index"), NULL, true); ?>">Voltar</a>
</div>

<div class="grid_12">
	<div class="block-border">
		<div class="block-header"> <h1>Formulário de Cadastro</h1><span></span> </div> 
		<div class="block-content">
			<?php echo $this->form;?>
		</div>
	</div>
</div>