<div class="grid_12">
	<h1>Usuários</h1>
	<p>Lista de usuários com acesso ao painel administrativo</p>
</div>
<div class="grid_12">
	<a class="button" href="<?php echo $this->url(array("module"=>"configuracao","controller"=>"usuarios","action"=>"index")); ?>">Voltar</a>
</div>

<div class="grid_12">
	<div class="block-border">
		<div class="block-header"> <h1>Formulário de Cadastro</h1><span></span> </div> 
		<div class="block-content">
			<?php echo $this->form;?>
		</div>
	</div>
</div>
