<div class="grid_12">
	<h1>Usuários</h1>
	<p>Lista de usuários com acesso ao painel administrativo</p>
</div>

<div class="grid_12">
	<div class="block-border">
		<div class="block-header"> <h1>Confirmação de Dados</h1><span></span> </div> 
		<div class="block-content">
			<ul class="block-list">
				<li><span>Nome:</span> <?php echo $this->info["nome"];?></li>
				<li><span>E-Mail:</span> <?php echo $this->info["email"];?></li>
				<li><span>Usuário:</span> <?php echo $this->info["login"];?></li>
				<li><span>Status:</span> <?php echo ($this->info["status"] == 1 ? "Ativo" : "Inativo");?></li>
			</ul>
			<h3>Você confirma a exclusão deste registro ?</h3>
			<a class="button" href="<?php echo $this->url(array("module"=>"configuracao","controller"=>"usuarios","action"=>"excluir","checked"=>true));?>">
				Sim, confirmo a exclusão
			</a>
			<a class="button" href="<?php echo $this->url(array("module"=>"configuracao","controller"=>"usuarios","action"=>"index"), NULL, true); ?>">
			Voltar
			</a>
		</div>
	</div>
</div>