<div class="grid_12">
	<h1>Base de Dados</h1>
	<p>Informações configuradas para conexão do seu banco de dados</p>
</div>
<div class="grid_12">
	<div class="alert <?php echo $this->statusType;?>"><?php echo $this->statusMsg;?></div>
	<?php foreach ($this->notificacao as $msg) :?>
		<div class="alert success flashMessage"><?php echo $msg; ?></div>
	<?php endforeach;?>
</div>
<div class="grid_12">
	<div class="block-border">
		<div class="block-header"> <h1>Informações</h1><span></span> </div> 
		<div class="block-content">
			
			<ul class="block-list">
				<li>
					<span>Servidor:</span>
					<?php echo $this->config->webhost;?>
				</li>
				<li>
					<span>Usuário:</span>
					<?php echo $this->config->database->params->username;?>
				</li>
				<li>
					<span>Senha:</span>
					*******************************
				</li>
				<li>
					<span>Base de Dados:</span>
					<?php echo $this->config->database->params->dbname;?>
				</li>
			</ul>
			<a class="button" href="<?php echo $this->url(array("module"=>"configuracao","controller"=>"database","action"=>"editar"));?>">Alterar Informações</a>
		</div>
	</div>
</div>
