<div class="grid_12">
	<h1>Google Analytics</h1>
	<p>Configurações para integração de relátorios de acesso</p>
</div>
<div class="grid_12">
	<a class="button" href="<?php echo $this->url(array("module"=>"configuracao","controller"=>"analytics","action"=>"index")); ?>">Voltar</a>
	<?php if (!$this->statusConsulta && isset($this->statusConsulta)) :?>
		<div class="alert error"><?php echo $this->erroConsulta; ?></div>
	<?php endif;?>
</div>

<div class="grid_12">
	<div class="block-border">
		<div class="block-header"> <h1>Formulário de Cadastro</h1><span></span> </div> 
		<div class="block-content">
			<?php echo $this->form;?>
		</div>
	</div>
</div>

<?php if($this->statusConsulta) :?>
<div class="grid_12">
	<div class="block-border">
		<div class="block-header"> <h1>Profiles Google</h1><span></span> </div> 
		<div class="block-content">
			<table class="table">
				<thead>
					<tr>
						<th>Título</th>
						<th>Profile</th>
						<th>Chave Web</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($this->resultado as $valor) :?> 
						<tr>
							<td><?php echo $valor->title;?></td>
							<td><?php echo $valor->profileId?></td>
							<td><?php echo $valor->webPropertyId?></td>
							<td>
								<a class="button-table view" href="<?php echo $this->url(array("module"=>"configuracao","controller"=>"analytics","action"=>"salvar","profile"=>$valor->profileId));?>">Selecionar</a>
							</td>
						</tr>
					<?php endforeach;?>					
				</tbody>
			</table>
		</div>
	</div>
</div>
<?php endif;?>