<div class="grid_12">
	<h1>Webmail</h1>
	<p>Nova Conta de E-Mail</p>
</div>
<div class="grid_12">
	<a class="button" href="<?php echo $this->url(array("module"=>"webmail","controller"=>"index","action"=>"index"), NULL, true); ?>">Voltar</a>
	<?php if(!empty($this->erro)) :?>
		<div class="alert error flashMessage"><?php echo $this->erro; ?></div>
	<?php endif;?>
</div>

<div class="grid_12">
	<div class="block-border">
		<div class="block-header"> <h1>Formulário de Cadastro</h1><span></span> </div> 
		<div class="block-content">
			<?php echo $this->form;?>
		</div>
	</div>
</div>